package initialize

import (
	"os"

	"go-generate/global"
	"go-generate/model/system"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.YAN_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	case "oracle":
		return GormOracle()
	case "mssql":
		return GormMssql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表

		system.SysDictionary{},
		system.SysAutoCodeHistory{},
		system.SysDictionaryDetail{},
		system.SysAutoCode{},

		// 示例模块表

		// 自动化模块表
		// Code generated by go-generate Begin; DO NOT EDIT.

		// Code generated by go-generate End; DO NOT EDIT.
	)
	if err != nil {
		global.YAN_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.YAN_LOG.Info("register table success")
}
